### ISSUE TITLE
"return home" navigation button needed on top-left of page

### ISSUE THREAD

**Issue by holaymolay** [jsdesigns-web-development/DEV-frs-mamapurnis.catering#4]
Mama Purni's has a UX issue.

When navigating to the other pages (e.g events, personal chef, etc) returning back to the home page feels a little clumsy. Let's think of a solution that will allow the visitor to easily navigate back to the home page. 

My recommendation would be to show a back-arrow floating at the top-left of the screen. The back error goes to the previous page (index.html).

Then, as you scroll down the page it becomes an up-arrow that will scroll back up to the top of the page.

I feel like i've seen widgets like this on websites before. What do you think?

**Comment by holaymolay** [comment]
Ok Cool. Ya, a floating back-arrow will be enough on the other three pages.

**Comment by zsediqyar** [comment]
done
